version: '3.8'

services:
  db:
    image: mysql@sha256:dce31fcdd15aaedb5591aa89f19ec37cb79981af46511781fa41287d88ed0abd
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - 6379:6379