---
name: rainbow
version: '3.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 88e86e0b67262f9ab6244a356e81dd9ca8c55b37
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
